version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    env_file:
      - .env
    volumes:
      - '.:/myapp'
    depends_on:
      - redis
      - database

  # sidekiq:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/myapp
  #   entrypoint: sidekiq-entrypoint.sh
  #   environment:
  #     - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  #   env_file:
  #     - .env
  #   depends_on:
  #     - app
  #     - database
  #     - redis

  redis:
    image: redis:7
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  database:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
     - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  redis:
  postgres:
